from __future__ import annotations

from typing import Protocol

from app_deteccion.domain.entities import CriticalProductCase
from app_deteccion.domain.events import DomainEvent


class CaseRepository(Protocol):
    def add(self, case: CriticalProductCase) -> CriticalProductCase: ...
    def update(self, case: CriticalProductCase) -> CriticalProductCase: ...
    def get(self, case_id: str) -> CriticalProductCase | None: ...
    def list_all(self) -> list[CriticalProductCase]: ...
    def clear(self) -> None: ...


class EventPublisher(Protocol):
    def publish_many(self, events: list[DomainEvent]) -> None: ...
    def list_all(self) -> list[DomainEvent]: ...
    def clear(self) -> None: ...
